### ISSUE TITLE
Settings.ini missing

### ISSUE THREAD

**Issue by KnightTim** [anonymous1184/bitwarden-autotype#10]
If you install on a limited (non-admin) user account the settings.ini file will end up in the admin user AppData folder, and has to be copied to the non admin's profile manually.

**Comment by anonymous1184** [comment]
Did you used "Run As..." with the installer?

**Comment by KnightTim** [comment]
I just double clicked the installer and it prompted for admin permissions so I used my admin account to authenticate and installed as normal.

**Comment by anonymous1184** [comment]
That's the intended behavior of such functionality. Only the user that was able to elevate the installer should be able to use it, that's why it uses the _current user_ to grab environment variables.

Other installers get around this issue by not creating a profile at all and only on first run the profile is created, which is what I'm gonna do in order to avoid any workaround that might look suspicions in the code.

Thanks a lot for your input.

**Comment by anonymous1184** [comment]
The latest release fixes this.
