### ISSUE TITLE
"A referral was returned from the server" error.

### ISSUE THREAD

**Issue by Elrondolio** [anonymous1184/bitwarden-autotype#14]
Hello.  Trying to install Bitwarden Auto-type tonight on a new Windows install.  V1.0.1 has been working wonderfully for months until tonight.  Its installer will not work anymore as it only provided the option to download the newer 1.1.1 or quit.  Proceeded to download 1.1.1 setup.exe but after installing it, am receiving this error when loading auto-type:

> C:\Program Files]Auto-Type\bw-at.exe
> 
> A referral was returned from the server.

The only option in that dialog is "OK" and when pressed the program quits.

Unfortunately the 1.0.1 doesn't install anymore so am stuck.  Thanks for reading and looking forward to any guidance on what the issue is.

https://i.imgur.com/ZZ6GnUD.png

**Comment by anonymous1184** [comment]
[Seems like that is a Windows issue](https://www.technipages.com/windows-a-referral-was-returned-from-the-server-error-fix). There's lots of people commenting in the article that got around the problem, I checked those keys and looks like those values are the defaults (I'm on W10 x64 21H1, latest build).

If you don't feel confident changing them perhaps you might want to try and copy the Bitwarden CLI into `%AppData%\Auto-Type` directory. Why? When running executables from `%ProgramFiles%` security is hardened a bit, so that might be the case.

Another option is to temporarily disable security software (Anti-virus and/or Defender), if the issue is triggered by that you can safely whitelist the Bitwarden CLI executable.

**Comment by Elrondolio** [comment]
Thank you for the response.

To test, I moved the bw.exe into `%AppData%\Auto-Type` but that had no effect, the issue remained.  I also temporarily disabled windows defender (virus and firewall) and that too had no effect, the issue remained.

I am a bit warry of changing the default security settings to get around this issue, mainly as I don't have a clear understanding of what that'll mean for other apps moving forward.  Do you have any ideas why the 1.1.1 update triggered this issue where 1.0.1 did not?  Is there any way to revert to 1.0.1 instead of the latest update (installed via setup.exe) without the attempt to do so being blocked?

Again, thank you for your insight here... hope you are having a nice weekend.

**Comment by anonymous1184** [comment]
Hey! just finished with the API login and I tough that maybe your issue can be a byproduct of the files being signed. I sign the executables to get a lower false-positive rate in VirusTotal.

Given the fact that this done merely as a helper I cannot afford to buy a certificate for signing, thus I use self-signed certificates and perhaps a somewhat strict configuration is getting in the way (or Windows being Home?). If you're willing to try, [here][1]'s an unsigned debug version of the current develop branch. Please feel free to inspect the code on the executable and you can block network communications it via firewall if you feel more comfortable.

If it fixes you issue I have prepared a commit for an updated build script that creates both signed and unsigned versions. Other than that from version 1.1.1 the final executables use [BinMod](https://github.com/AutoHotkey/Ahk2Exe/blob/master/BinMod.ahk) (again to get less false positives from AV engines), [here][2] is a version without BinMod.

Finally [here][3] is the most vanilla version which uses the U64 .bin base file in the AutoHotkey distribution rather than the one I modified for the project (I removed the unnecessary bits).

Hopefully one of them has the answer for you and most likely to others facing the sane issue. If you are able to have any of them working I'd know what to do to fix the problem.

Thanks a lot for your patience and input.

[1]: https://github.com/anonymous1184/bitwarden-autotype/files/7316671/bw-at-unsigned.zip
[2]: https://github.com/anonymous1184/bitwarden-autotype/files/7316672/bw-at-unsigned-no-BinMod.zip
[3]: https://github.com/anonymous1184/bitwarden-autotype/files/7316673/bw-at-unsigned-vanilla.zip

**Comment by TSnatch72** [comment]
> 
> Given the fact that this done merely as a helper I cannot afford to buy a certificate for signing, thus I use self-signed certificates and perhaps a somewhat strict configuration is getting in the way (or Windows being Home?). If you're willing to try, [here](https://github.com/anonymous1184/bitwarden-autotype/files/7316671/bw-at-unsigned.zip)'s an unsigned debug version of the current develop branch. Please feel free to inspect the code on the executable and you can block network communications via firewall if you feel more comfortable.
> 

Just tried this build and the problem is now gone completely. Haven't tested the others, though.

**Comment by Elrondolio** [comment]
Well, that was interesting results.  I downloaded your new build setup.exe, v1.1.2 and installed it.  Same issue as before: running it from its shortcut or directly from `C:\Program Files]Auto-Type\bw-at.exe` where it was installed results in the same "referral" issue.  I then downloaded the zip of v1.1.2 and replaced the bw-at.exe in the same location, `C:\Program Files]Auto-Type` and it worked as normal (with the new UI you built to support API login, which works just fine thank you!).  I also downloaded all three of your above debug builds and all of them work fine as well (all displaying 'Debug version' on startup).

Not sure what that means, exactly or why these results.  Let me know if this helps or if there is anything else I can do to help test.  Thanks again for your excellent work on this invaluable app, the new API login correctly bypasses their new Captcha requirement with username and password.

**Comment by anonymous1184** [comment]
Looks like a problem of the CA chain resolution algorithm. But I cannot seem to find a solution.

Having a somewhat complete Distinguished Name in the CA (Certification Authority) ***might*** work. My problem relies in the fact that I cannot reproduce the issue.

[This][1] is literally just a `Hello World` message, if anyone in the thread care to run it and reply with the findings would be awesome, otherwise I have to revert and release unsigned executables resulting in higher false-positives rate in VirusTotal.

[1]: https://github.com/anonymous1184/bitwarden-autotype/files/7316902/Hello.zip

**Comment by Elrondolio** [comment]
When downloading the setup.exe for 1.1.2 using Edge (temporarily using Edige to test memory usage) it does get blocked and requires unblocking to complete the download.  Also, when running, get another block from Defender and must unblock that as well to install.

When attempting to download your Hello World, it gets blocked by Defender (Severe) as `Trojan:Script/Sabsik.FL.A!ml`

https://i.imgur.com/dQkFumc.png

**Comment by KnightTim** [comment]
These are the VirusTotal results from the Hello World message, it's flags it. 
[Link](https://www.virustotal.com/gui/file/602897ebdef508349c251ad43150e9dea97b64b99b94e8b930b784e57e1777a4?nocache=1)

![Screenshot 2021-10-10 at 01-20-45 VirusTotal - File - 602897ebdef508349c251ad43150e9dea97b64b99b94e8b930b784e57e1777a4](https://user-images.githubusercontent.com/858797/136685037-56bf3770-4236-41fc-82cb-0142c3731f87.png)
=

**Comment by anonymous1184** [comment]
That's how dumb are AV engines nowadays... this is the source code of the `Hello.exe`:

```ahk
MsgBox 0x40, Test, Hello World!
```

Yet is only flagged by **Zillya** which until I did this tests never heard of it, but Defender says is "_Severe_".

That will be the tradeoff: higher false positive rate vs random issues.

Still the setup version should work as the certificate is created by the host machine via PowerShell. So, the issue remains, why signed executables with a certificate created by the host machine gives this error? Perhaps is Windows Home or a some processor instruction set (currently I own only AMD-based PCs).

The current state of the develop branch adds a more complete DN as was the only viable fix I could think of that made sense. Most of the online information I've found is either policies too strict or wacky DN strings. This will fix the latter if that's the issue, I was previously generating the certificate via AutoHotkey itself but Windows 11 break that.

This are builds from the develop branch

- [bw-at.zip](https://github.com/anonymous1184/bitwarden-autotype/files/7318319/bw-at.zip)
- [bw-at-unsigned.zip](https://github.com/anonymous1184/bitwarden-autotype/files/7318320/bw-at-unsigned.zip)
- [setup.zip](https://github.com/anonymous1184/bitwarden-autotype/files/7318321/setup.zip)
