### ISSUE TITLE
an error occured

### ISSUE THREAD

**Issue by Nypheena** [anonymous1184/bitwarden-autotype#15]
`{
	"A_Error": {
		"Extra": "Unexpected character at position 1: 'Y'",
		"File": "bw-at.exe",
		"Line": 833,
		"Message": "Failed to parse JSON (-1,0)",
		"What": "-1"
	},
	"A_Info": {
		"locked": 0,
		"logged": 1,
		"portable": 1,
		"status": "unauthenticated",
		"sync": null,
		"version": "1.1.1.1",
		"windows": "10.0.19041"
	},
	"ADVANCED": {
		"field": "auto-type",
		"NODE_EXTRA_CA_CERTS": "",
		"pin-length": "4",
		"reprompt-with-pin": "1",
		"server": "",
		"tcato-ksps": "10",
		"tcato-wait": "250",
		"update-frequency": "1"
	},
	"CREDENTIALS": {
		"tsl": 2,
		"user": "Present"
	},
	"DATA": {
		"pin": "",
		"update": "1633742864",
		"version": "1.0"
	},
	"GENERAL": {
		"action": "0",
		"favicons": "0",
		"pin": "0",
		"sync": "15",
		"tcato": "1",
		"timeout": "0",
		"totp": "2",
		"updates": "1"
	},
	"GENERATOR": {
		"digits": "1",
		"exclude": "",
		"length": "39",
		"lower": "1",
		"symbols": "1",
		"upper": "1"
	},
	"HOTKEYS": {
		"default": "^!a",
		"password": "+^!s",
		"totp": "^!o",
		"username": "^!u"
	},
	"SEQUENCES": {
		"default": "{ClearField}{Username}{SmartTab}{Password}{Enter}",
		"password": "{ClearField}{Password}{Enter}",
		"totp": "{TOTP}",
		"username": "{ClearField}{Username}"
	}
}`

**Comment by nefrog** [comment]
I'm also getting this error with both the portable and stand alone version. The error seems to occur when attempting to sync with bitwarden.
v 1.1.1.
![image](https://user-images.githubusercontent.com/50126479/136663483-74e34135-584f-4bd9-b341-5f14cb5ac453.png)

**Comment by anonymous1184** [comment]
Seems to be an error because of the new bot detection on Bitwarden CLI. I'm going to report the issue but for now seems that the only workaround would be to log via API Key. However even that has a lot of issues for the moment being:

So far issues [383](https://github.com/bitwarden/cli/issues/383) and [384](https://github.com/bitwarden/clients/issues/2734) are related to this and the one I'm about to report make it the 3rd.

**EDIT:** [Here](https://github.com/bitwarden/clients/issues/2733) is the issue 385 (created by me), which is what's happening in this case.
