### ISSUE TITLE
Doesn't Auto-Fill Executable Logins Properly

### ISSUE THREAD

**Issue by NoFreeWill** [anonymous1184/bitwarden-autotype#26]
Not sure why this is happening, it was working for a while and now does not. I get No Auto-Type Found error on this window... the same issue applies to discord (on Win x64) I added all the possible .exe I could find related to it, not sure why it doesn't work.

![2022-04-11 08_32_44-](https://user-images.githubusercontent.com/2538910/162777040-3a87f080-34f1-4a31-943f-cf3a7f7c2b6a.png)
.

**Comment by anonymous1184** [comment]
After testing this appears to be the same as #25, which ultimately turned out to be a bug in Bitwarden CLI application.

Long story short if you don't want to go through all the comments, you need to make sure the Bitwarden CLI app is returning data to feed the Auto-Type application, [this comment][1] has the fixes.

Sorry for the inconvenience but is out of my hands, hopefully the next Bitwarden release fixes the issue. As for my part, I'll add an update notifier for the CLI tool so users keep the latest binary if desired.

[1]: https://github.com/anonymous1184/bitwarden-autotype/issues/25#issuecomment-1081202884
