### ISSUE TITLE
Using shift+tab in custom field execute normal tab

### ISSUE THREAD

**Issue by lesourcil** [anonymous1184/bitwarden-autotype#27]
When i try to run this custom auto-type with a shift-tab it execute a normal tab instead.

{ClearField}{Username}{Tab}{ClearField}SOMETHING{Tab}{ClearField}{Password}{Tab}{Space}+{Tab}+{Tab}{Right}

**Comment by anonymous1184** [comment]
Thanks for the report... I'm addressing the issue and will be fixed on the next release.

**Comment by anonymous1184** [comment]
Is fixed now in the develop branch and should be ready to roll in the next release.

Unfortunately as you seen from my late response, free time has been hard to come by and the next release is a bit overdue. What you can do is clone the repo and build, if is something you don't want to I can do that for you and attach the develop build to this thread.

Now in order for your custom sequence to work you would need to specify the `Down`/`Up` state of the key (<kbd>Shift</kbd> in this case). 

**Why the key paired with the state rather than just the modifier signs?**

Because it removes the ambiguity, for example, in you use `+{Tab}{Right}`. Meaning that without explicitly use the down/up state you could end up selecting one character to the right or moving the cursor one character to the right.

Imagine if you use something like `+{Tab}{Password}`, it might mean <kbd>Shift</kbd>+<kbd>Tab</kbd> then normally type the password or keep held <kbd>Shift</kbd> while typing the password... so explicitly hold and release the key is better suited:

```
; For Shift with 2 Tabs then move caret one character to the right:
{ClearField}{Username}{Tab}{ClearField}SOMETHING{Tab}{ClearField}{Password}{Tab}{Space}{Shift Down}{Tab 2}{Shift Up}{Right}

; For Shift with 2 Tabs AND right arrow to have a character selected:
{ClearField}{Username}{Tab}{ClearField}SOMETHING{Tab}{ClearField}{Password}{Tab}{Space}{Shift Down}{Tab 2}{Right}{Shift Up}
```

**Comment by lesourcil** [comment]
Hi, thx for the update,  I built from dev and it works like a charm.
