### ISSUE TITLE
Fix for Master-Passwords with spaces

### ISSUE THREAD

**Issue by Christoph-AK** [anonymous1184/bitwarden-autotype#3]
My Master-Password with spaces didn't get accepted.

Enclosing the password in double quotes by changing line 268 in bw-at.ahk to 

    login := "login " bwUser " """ bwPass """"

does fix the problem for me.

**Comment by anonymous1184** [comment]
You're right, never tested spaces since back in the day services I used regularly didn't accepted spaces (I remember Usenet, IRC and ICQ), thus for me, the space was kind of a "forbidden" character in passwords. Now, I have a function (CNG based) to generate passwords from all the ASCII printable characters (33 to 126). 

Thanks a lot for your input. However I can't do it right now and it still needs to validate quotes and properly escape them. I guess it'll be something along the lines of:

```ahk
    quote := Chr(34)
    if (InStr(bwPass, quote))
    {
        bwPass := StrReplace(bwPass, quote, quote quote)
    }
    login := "login " bwUser A_Space quote bwPass quote
```

**Comment by Christoph-AK** [comment]
> the space was kind of a "forbidden" character in passwords.
That is why I like to use the thing in passwords so much, most people wouldn't think of trying it out and it makes for easy to remember, but long passwords 😄

Thanks for developing this!

**Comment by anonymous1184** [comment]
Latest release takes care of this an much more.
