### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by hspindel** [anonymous1184/bitwarden-autotype#41]
I can't get this to install.

First problem was that the scripts seems to assume that AutoHotKey is installed on C:.  I had it on D:.  Uninstalled and reinstalled to C: and made progress.

Then the build.ahk script reports an error as shown in the attached JPG.  (I couldn't copy and paste from the dialog box.)  I tried moving the installation files to C: but it didn't help.

I would really like to use this utility!

![bitwarden_autotype](https://user-images.githubusercontent.com/11689573/209314989-af3bb2ab-0548-4305-92db-5f0f108a9fac.jpg)

**Comment by anonymous1184** [comment]
Hello @hspindel, thanks for the interest in the app.

> I would really like to use this utility!

If you use the [precompiled binaries][1], you don't need to change the installation path of AutoHotkey in order to manually build.

[1]: https://github.com/anonymous1184/bitwarden-autotype/releases/latest

---

The image shows that build script can't find the compiler in the default path, also shows the path to be `%ProgramFilesX86%` which is for SysWOW64 (32bit apps running under x64). AutoHotkey by default installs in `%ProgramFiles%`, that's why the error.

You either are removing the compiler after the installation, or running the build script with the 32bit version of AHK from a SySWOW64 parent process that inherits the wrong path to the build script.

I cloned the repo and managed to replicate the latter:

![20221224010559](https://user-images.githubusercontent.com/53758552/209425342-c28b1db5-5416-4a2f-bcc1-bbde2146e758.png)

The solution for the first issue would be to not remove the compiler, the solution for the second would be to use the x64 version of AHK:

- Press <kbd>Win</kbd>+<kbd>r</kbd>.
- Type `cmd`, and press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>.
    - Accept the UAC prompt.
- Call the build script with AHK's x64 binary:

![20221224005315](https://user-images.githubusercontent.com/53758552/209425364-7a522479-8225-413e-b559-678cfd194f84.png)

If you notice, after the repo was cloned, I manually created a directory. That is a bug I just find, however I'm not fixing it as I'm a few days away of pushing a big update that will take care of that.

Thanks for your report, as the new build script also had the same issue (even if it was completely rewritten). Also, I'll make sure the build script doesn't run into this issue anymore.

**Comment by hspindel** [comment]
I hadn't noticed that there were precompiled binaries available.  That is the best solution for me.

Thank you!!

**Comment by anonymous1184** [comment]
Glad it worked out. Again, thanks for shed light into a bug that would have released again.

**Comment by hspindel** [comment]
I used the precompiled binary to install bitwarden-autotype.  It installed okay to 
c:\Program Files\Auto-type\bw-at.exe.

Made a lot of progress.  One thing: I can't find bw-at.ini anywhere on my computer.  Where are the settings stored?  They are obviously stored somewhere because they are remembered across invocations.

I want to use this with Quicken.  I created a URI match in Bitwarden.  I entered my Quicken password in the password field.  I tried URI-1 equal to either Quicken Premier (the main window title) or Enter Vault Password (the subsidiary Quicken popup), and tried both "starts with" and "exact".  Then I tried adding two URIs, one for 
"Quicken Premier" and one for "Enter Vault Password".  No joy.

I had changed the settings for the auto-type hotkey to be Win/Alt+A.  When I hit Win/Alt+A in Quicken it says "no auto-type match found."  What am I missing?  Possibly something about how to format the URIs so they are recognized?

I couldn't find a log file to help debug this.

Thank you for any further help.

Howard

**Comment by hspindel** [comment]
Found the problem.  I had to right-click the taskbar icon and click "sync" after modifying the bitwarden logins.

**Comment by anonymous1184** [comment]
Yes, the app is installed in `%ProgramFiles%\Auto-Type` as it is a protected directory. The settings are stored per-user in the "Application Data" profile directory (`%AppData%\Auto-Type`) which maps to:

    C:\Users\<USERNAME>\AppData\Roaming\Auto-Type

In there you'll find 2 files: `data.json` and `settings.ini`. The first one is Bitwarden's encrypted vault and the second the settings for the Auto-Type app.

If you want to edit settings via its configuration file, make sure to either have the app closed or reload it after you change anything. A better option would be to use the built-in settings UI.

As for your issue with Quicken, you only need to add a URL to an existent login entry. For example, this is are my URLs for the Bitwarden Community Forum:

![20221226002357](https://user-images.githubusercontent.com/53758552/209511429-7fba14be-3bc1-4317-8c5e-17fe9c4d7a52.png)

As it is, it'll match in a browser and an application whose executable is `Notepad3.exe`.

With that in mind, you only need to add the Quicken executable and that's it.

**Comment by hspindel** [comment]
Got it working.  Thank you for all your help, and for providing a much needed add-on to Bitwarden.
