### ISSUE TITLE
Windows 11 Hotkeys did not recognized

### ISSUE THREAD

**Issue by huggenknubbel** [anonymous1184/bitwarden-autotype#46]
Hello,
i don't know what i'm doing wrong, but the Hotkeys sometimes did not work since i use Windows 11. 
sometimes they work, and after a restart, they don't. 
i have to change the hotkey to an other binding and then, sometimes, they will work again.

**Comment by anonymous1184** [comment]
I've been using the tool (personally) with W11 for months now, no issues. Before that, since W11 was development release, people were using it without any problem on the hotkeys front.

Would you mind telling me if you are installing or using the portable version, also which hotkeys are you using?

**Comment by huggenknubbel** [comment]
i use AltGr + \ as my hotkey. thats sometimes does't work anymore. 
AltGr + F10 is working. as far as i can tell.
i use Autohotkey with a a different keyboardlayout: https://eurkey.steffen.bruentjen.eu/?lang=de
There is on the "\" key the "¬" symbol but the settings window show it as an other hotkey: 
![grafik](https://user-images.githubusercontent.com/15655280/224683447-c4e08897-5305-4a70-8a99-75be89695d70.png)

maybe thats the Problem?

**Comment by anonymous1184** [comment]
That would be the problem, <kbd>AltGr</kbd> is not a key _per se_ but a weird combination of keys meaning: "left <kbd>Control</kbd> plus right <kbd>Alt</kbd>", sometimes "left <kbd>Control</kbd> plus left <kbd>Alt</kbd>" and even just <kbd>Alt</kbd> (but that one also depends on the application).

It will prove almost impossible to add it into this UI. Not just because space constrains, but because I'll need a keyboard that has the key (I don't own one), and use all the different layouts that make sense of the key (as not all of them work the same). As I recall in a Spanish ISO keyboard I had, it was just <kbd>Alt</kbd> if I used European layout but with Latin layout it was <kbd>Ctrl</kbd>+<kbd>Alt</kbd>. Lastly, not all applications respond equally to the key, so it will still be impossible to get it 100% working.

On top of that, you are combining <kbd>AltGr</kbd> with the `Numpad` keys (that have a different meaning depending on if the <kbd>NumLock</kbd> is toggled or not).

My advice would be to not use that key, given how erratic its behavior is. If still want to use it, try manually editing the configuration file:

```ini
[HOTKEYS]
default  = <^>!\
username = <^>!Numpad9
password = <^>!Numpad8
totp     = <^>!Numpad7
```

Links to the key names and the meaning of the symbols is inside the configuratin file.

Hope that helps!

**Comment by huggenknubbel** [comment]
Nice, thank you! 
The Config file was the correct hint!
While i  experimenting with different Hotkeys, i rebind `F13` - `F24` to a second Layer on my Keyboard and configured this keys in the config file. 
The GUI didn't recognized this funktion keys but thats okay for me.

**Comment by anonymous1184** [comment]
Glad you got not just your issue solved but also improved upon.

The level of customization one achieves with AHK is so underwhelming... thus, a one-fits-all solution is never achievable, one can only think of so many scenarios :P
